
trigger:
- develop

steps:
- task: NodeTool@0
  inputs: 
   versionSpec: '10.x'
   
  displayName: 'Install Node.js'

- script: |
   yarn install
   
   npm install -g expo-cli
   npm install -g turtle-cli
   npx expo login -u $(EXPO_CLI_USER) -p $(EXPO_CLI_PASSWORD) 
   
   npx expo publish --non-interactive --release-channel deployment
   
   turtle setup:android
   EXPO_ANDROID_KEYSTORE_PASSWORD=$(EXPO_ANDROID_KEYSTORE_PASSWORD) EXPO_ANDROID_KEY_PASSWORD=$(EXPO_ANDROID_KEY_PASSWORD) turtle build:android -u $(EXPO_CLI_USER) -p $(EXPO_CLI_PASSWORD) --keystore-path <keystore_path> --keystore-alias $(keystore-alias) -t apk --release-channel deployment 
   
   cd /users/vsts/expo-apps
   export A=$(ls *.apk)
   echo "##vso[task.setvariable variable=androidArtifact]$A"
   echo "File name to publish Android"
   echo $A
  displayName: 'npm install and Expo & turtle build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "/users/vsts/expo-apps/$(androidArtifact)"
    ArtifactName: 'android'
    publishLocation: 'Container'
    
  displayName: 'Publish Android'
